#! /bin/sh
### BEGIN INIT INFO
# Provides:          zesap
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Run zesap jobs
# Description: middleware soft to server
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
#ZESAPPATH="/usr/sbin/zesap"
ZESAPPATH="/home/zelder/Projects/Zexes/zesap/bin/zesap"

case "$1" in
  start)
    echo "Starting zesap cron" "zesap"
    start-stop-daemon --start --exec $ZESAPPATH
    log_end_msg 0
    ;;
  restart|force-reload|reload)
	# nothing to do
    :
    ;;
  stop)
    echo "Stopping zesap cron" "zesap"
    start-stop-daemon --stop --exec $ZESAPPATH
    log_end_msg 0
    ;;
  status)
    exit 4
    ;;
  *)
    echo "Usage: /etc/init.d/zesap {start|stop|restart}"
    exit 2
    ;;
esac

exit 0
